### ISSUE TITLE
10-05-2020: As a visitor, I would like to see the Urban Population for a specific country.

### ISSUE THREAD

**Issue by codemis** [MobMin/digital_atlas#6]
## Description

Users would like to view the urban population on countries where the data exists.  If the country data does not exist, simple state "Sorry, but no data exists.".

## Solution

We would like to develop a widget that displays urban population for the specific country.  Here are some possible data source: 

- [World Bank](https://data.worldbank.org/indicator/SP.URB.TOTL.IN.ZS) - Note the online chart does not provide country specific data, but the CSV does.

It should display a chart of urban population for the last 5 years.

## Additional Information

To develop a widget, please look at the [Project Wiki](https://github.com/MobMin/digital_atlas/wiki/Widgets) for more details.  **Please add attributions to the footer of the widget, so we know where the data is retrieved from.**

**Comment by vo689bj** [comment]
Hello, I would like to try to working on this issue. Could you assign it to me please? Thank you
